project:
  type: book

book:
  title: "Behind GDP"
  author: "Luis Biedma"
  date: "10/12/2023"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-production.qmd


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

